### ISSUE TITLE
博客主题写的好漂亮

### ISSUE THREAD

**Issue by zzsme** [overtrue/overtrue.github.io#3]
发现一个问题，查看源代码，多了几个</head>标签

**Comment by overtrue** [comment]
@zzsme 哪个位置？

**Comment by zzsme** [comment]
![image](https://cloud.githubusercontent.com/assets/2157390/9458115/42590ee8-4b1d-11e5-839d-1d3adfadea83.png)

**Comment by overtrue** [comment]
@zzsme 多谢！

**Comment by zzsme** [comment]
不客气

有礼行天下，有德立江湖，有才游四方，有品聚贤能！

2015-08-25 11:52 GMT+08:00 安正超 <notifications@github.com>:
